language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

addons:
  hosts:
    - pug.app

before_script:
  - composer install --prefer-source --no-interaction
  - php -S pug.app:8000 -t public &
  - sleep 3

script: vendor/bin/behat