language: php

php:
  - 5.6
  - 7.0

addons:
  hosts:
    - pugs.app

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-source --no-interaction
  - php -S pugs.app:8000 -t public &
  - sleep 3

script: vendor/bin/behat --profile=travis
